In [1]:
import numpy as np

In [2]:
np.random.seed(42)
heights=np.random.randint(3,8,30)
weights=4+20*heights+np.random.random(30)*20

In [3]:
heights

array([6, 7, 5, 7, 7, 4, 5, 5, 5, 7, 6, 5, 7, 4, 6, 4, 6, 7, 3, 6, 4, 7,
       6, 3, 3, 5, 5, 4, 6, 6])

In [4]:
weights

array([131.32723687, 153.12139968, 119.70351923, 147.99347564,
       154.28468877,  95.84829138, 104.92900825, 116.15089704,
       107.41048247, 145.30103186, 142.97771075, 123.31264066,
       160.16794696,  90.09227538, 125.95344228,  97.68466053,
       132.80304987, 146.4407647 ,  73.9035382 , 124.68777042,
       102.18640804, 149.17559963, 137.25044569,  70.23422152,
        74.40136042, 114.93420559, 107.69708911, 103.39169256,
       139.50265647, 142.78997883])

In [5]:
from sklearn.linear_model import LinearRegression

In [7]:
linear_model=LinearRegression()

In [8]:
linear_model.fit(heights,weights)

ValueError: Expected 2D array, got 1D array instead:
array=[6 7 5 7 7 4 5 5 5 7 6 5 7 4 6 4 6 7 3 6 4 7 6 3 3 5 5 4 6 6].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [11]:
heights=heights.reshape(-1,1)

In [12]:
linear_model.fit(heights,weights)

LinearRegression()

In [13]:
linear_model.intercept_

19.16279255029727

In [14]:
linear_model.coef_

array([19.01101685])

In [15]:
linear_model.predict(heights)

array([133.22889363, 152.23991048, 114.21787678, 152.23991048,
       152.23991048,  95.20685994, 114.21787678, 114.21787678,
       114.21787678, 152.23991048, 133.22889363, 114.21787678,
       152.23991048,  95.20685994, 133.22889363,  95.20685994,
       133.22889363, 152.23991048,  76.19584309, 133.22889363,
        95.20685994, 152.23991048, 133.22889363,  76.19584309,
        76.19584309, 114.21787678, 114.21787678,  95.20685994,
       133.22889363, 133.22889363])

In [16]:
y_pred=linear_model.predict(heights)

In [21]:
from sklearn.metrics import mean_absolute_error,mean_squared_error, r2_score

In [22]:
mean_absolute_error(weights,y_pred)

5.064859289101606

In [23]:
mean_squared_error(weights,y_pred)**0.5

5.868878189839377

In [24]:
r2_score(weights,y_pred)

0.9448334923706487

## Multiple linear regression

In [25]:
from sklearn.datasets import load_boston

In [26]:
bundle=load_boston()

In [28]:
print(bundle.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [29]:
bundle.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [31]:
y=bundle.target

In [34]:
X=bundle.data

In [35]:
X.shape

(506, 13)

In [37]:
X_rm=X[:,5].reshape(-1,1)

In [38]:
X_rm

array([[6.575],
       [6.421],
       [7.185],
       [6.998],
       [7.147],
       [6.43 ],
       [6.012],
       [6.172],
       [5.631],
       [6.004],
       [6.377],
       [6.009],
       [5.889],
       [5.949],
       [6.096],
       [5.834],
       [5.935],
       [5.99 ],
       [5.456],
       [5.727],
       [5.57 ],
       [5.965],
       [6.142],
       [5.813],
       [5.924],
       [5.599],
       [5.813],
       [6.047],
       [6.495],
       [6.674],
       [5.713],
       [6.072],
       [5.95 ],
       [5.701],
       [6.096],
       [5.933],
       [5.841],
       [5.85 ],
       [5.966],
       [6.595],
       [7.024],
       [6.77 ],
       [6.169],
       [6.211],
       [6.069],
       [5.682],
       [5.786],
       [6.03 ],
       [5.399],
       [5.602],
       [5.963],
       [6.115],
       [6.511],
       [5.998],
       [5.888],
       [7.249],
       [6.383],
       [6.816],
       [6.145],
       [5.927],
       [5.741],
       [5.966],
       [

In [39]:
def compute_model_values(X,y):
    model =LinearRegression()
    model.fit(X,y)
    y_pred=model.predict(X)
    rmse=mean_squared_error(y,y_pred)**0.5
    r2=r2_score(y,y_pred)
    return {"r2":r2,"rmse":rmse,"y_pred":y_pred,
            "intercept":model.intercept_,
            "coeff":model.coef_
           }

In [40]:
compute_model_values(X_rm,y)

{'r2': 0.48352545599133423,
 'rmse': 6.603071389222561,
 'y_pred': array([25.17574577, 23.77402099, 30.72803225, 29.02593787, 30.38215211,
        23.85593997, 20.05125842, 21.50759586, 16.5833549 , 19.97844155,
        23.3735282 , 20.02395209, 18.93169901, 19.47782555, 20.81583557,
        18.43108302, 19.35039603, 19.85101202, 14.99048582, 17.45715736,
        16.02812625, 19.6234593 , 21.23453259, 18.23993873, 19.25027283,
        16.29208741, 18.23993873, 20.36983223, 24.44757706, 26.07685456,
        17.32972783, 20.59738496, 19.48692766, 17.22050253, 20.81583557,
        19.33219181, 18.49479778, 18.57671676, 19.63256141, 25.35778795,
        29.26259271, 26.95065703, 21.48028953, 21.86257811, 20.57007863,
        17.04756245, 17.99418179, 20.21509638, 14.47166561, 16.31939374,
        19.60525508, 20.98877564, 24.5932108 , 19.92382889, 18.9225969 ,
        31.31056723, 23.42814085, 27.36935404, 21.26183891, 19.27757916,
        17.58458688, 19.63256141, 24.09259481, 26.87784015

In [43]:
X_comb1=X[:,[1,5]]

In [44]:
compute_model_values(X_comb1,y)

{'r2': 0.5063381295424694,
 'rmse': 6.455595711880293,
 'y_pred': array([25.40326897, 22.97309501, 29.43109362, 27.85040548, 29.10988427,
        23.04917091, 20.29950049, 21.65196093, 17.07895406, 20.23187747,
        23.38480087, 20.27414186, 19.25979653, 18.98333671, 20.22590974,
        18.01125576, 18.86499642, 19.32990469, 14.81606797, 17.10679784,
        15.77969603, 19.11858275, 20.61474211, 17.83374533, 18.77201476,
        16.02482949, 17.83374533, 19.81171873, 23.59860796, 25.11167308,
        16.98845755, 20.02304067, 18.99178958, 16.88702302, 20.22590974,
        18.84809066, 18.07042591, 18.14650181, 19.12703563, 29.14569066,
        32.77197522, 25.92314935, 20.84296981, 21.19799068, 19.99768204,
        16.72641834, 17.60551763, 19.6680198 , 14.33425394, 16.05018812,
        20.41817957, 21.70301699, 25.05035658, 20.71403029, 23.16950608,
        35.61423169, 27.98058656, 32.58104161, 22.20736572, 20.36463837,
        18.7924031 , 20.6943006 , 24.8362107 , 27.4227913 ,

In [45]:
X_comb2=X[:,[0,1,5]]

In [46]:
compute_model_values(X_comb2,y)

{'r2': 0.5558361794163031,
 'rmse': 6.123406943385556,
 'y_pred': array([26.05161482, 23.93614605, 29.99418638, 28.51014363, 29.6825837 ,
        24.00688466, 21.29549752, 22.55033746, 18.24412279, 21.21192504,
        24.1560672 , 21.26452149, 20.31883318, 20.04508335, 21.2086802 ,
        19.1337901 , 19.82958603, 20.33214399, 16.09330311, 18.26110653,
        16.8866285 , 20.11719876, 21.42698481, 18.87833809, 19.81716633,
        17.21788371, 18.95630676, 20.74185484, 24.33923505, 25.70206841,
        18.05032892, 20.84181525, 19.8662372 , 17.95002575, 20.96854201,
        20.05753582, 19.31983874, 19.39546456, 20.29189171, 29.02067674,
        32.4209065 , 26.67882956, 21.90981735, 22.23845124, 21.12151427,
        18.04084603, 18.86132722, 20.78601505, 15.77652554, 17.39458667,
        21.32673887, 22.54317603, 25.68068489, 21.61385387, 23.4180712 ,
        34.95103862, 27.83538188, 32.01131185, 22.95128922, 21.23529225,
        19.74908915, 21.52768108, 25.42820486, 27.85059282,